### ISSUE TITLE
Cannot download raw data

### ISSUE THREAD

**Issue by OnlyBelter** [cozygene/bisque#10]
I cannot download raw data from https://www.synapse.org/ although I have logged in with my own account.

I saw this information:
`
You do not have download access for this item.
`

Do I have another way to access this raw data and have a real test of your algorithm?

**Comment by OnlyBelter** [comment]
Or is there a demo dataset only for test?

**Comment by brandonjew** [comment]
Hi Xin,

Thanks for your interest in our method. The cortex dataset is part of the ROSMAP study. You can request access to the data here: https://www.radc.rush.edu/requests/data.htm

If approved, you can download the data from the synapse website.

If you're interested in the test/simulated data, you can generate it with the `SimulateData()` function as shown in the vignette: https://cran.r-project.org/web/packages/BisqueRNA/vignettes/bisque.html

Please let me know if you have any other questions.

Thanks again,
Brandon
