### ISSUE TITLE
BisqueRNA Functions not available for usage

### ISSUE THREAD

**Issue by Amandahsr** [cozygene/bisque#12]
Great tool for bulk tissue deconvolution, its a great package and estimates really well!

May I ask if some of the BisqueRNA functions will be made available for usage? e.g. GenerateSCReference and SemisupervisedTransformBulk functions

Or if these functions cannot be made available for usage, could I suggest adding an additional output from the ReferenceBasedMethod that returns the transformed bulk counts? This can help users to plot distributions of the transformed datasets and run statistical tests

**Comment by brandonjew** [comment]
Hi @Amandahsr 

Thanks for the feedback! Just pushed a commit that adds the `GenerateSCReference` to the exported functions and returns the transformed bulk in the `transformed.bulk` slot of the output of `ReferenceBasedDecomposition`. These changes will be live on CRAN/Bioconda within the next day or two. Let me know if you have any questions or other comments

Brandon

**Comment by Amandahsr** [comment]
Hi brandon, thanks for the additional functions! However, it doesn't seem like these commits are available yet in the BisqueRNA package in R.

**Comment by brandonjew** [comment]
Hi, the latest commits are live on CRAN for all operating systems. The package should be at version 1.0.4. You can make sure you have the latest version by running `install.packages("BisqueRNA")` again. Let me know if there's any issues.

Thanks!
