### ISSUE TITLE
Counts input for bulk RNAseq dataset

### ISSUE THREAD

**Issue by jdarmitage** [cozygene/bisque#14]
Hi,

Thanks for this super useful R package! Just wanted to clarify what input the bulk RNAseq data needs to be in before running BISQUE against a single cell reference profile? Do we pass the raw count matrix onto BISQUE or log/VST-transformed data?

Thanks for the help!

**Comment by brandonjew** [comment]
Hi,

Thanks for the feedback! The reference-based method utilizes the raw count matrix and internally performs CPM normalization.

Let me know if you have any other questions.

Thanks,
Brandon
