### ISSUE TITLE
Weird results ? 

### ISSUE THREAD

**Issue by alexdray86** [cozygene/bisque#18]
Hello ! 

I got very interested in your method after reading your publication. I was before relying on MuSiC to accomplish the same task. From the publication it seems that you can estimate cell type proportion with better accuracy. 

So I decided to test it in a very simple way : I have a scRNA-seq with 16 subjects. I used 8 subjects as a single-cell reference, and the 8 others to construct pseudo bulks (simply by summing up counts in each cells for each gene). I used music and bisque to find the known cell type proportions in these 8 pseudo bulks. What happened is that I am always getting higher correlation and lower error with music. Do you think I might be doing something wrong that prevents me to use the full capacity of BisqueRNA ? 

I lauched the following command : 

`BisqueRNA::ReferenceBasedDecomposition(pbulk.sub, sc_aml, use.overlap=F)` 

So the sc_aml is an ExpressionSet with raw counts at the single-cell level and pbulk.sub is for the pseudo-bulks I generated by summing up counts. I prefer to test it for the case where we don't have the paired single-cell / bulk, as this looks more similar to the real cases I have.

For exemple, do you think that using marker genes might improve the results ? Any leads ?

**Comment by brandonjew** [comment]
Hi @alexdray86,

Thanks for your interest in our method! For this simulation, we expect the performance of Bisque and MuSiC to be roughly equal (although not unexpected for MuSiC to perform better), as this should correspond to figure 2B with sigma=0. Marker gene selection may help here but it’s good to keep in mind that each method, including others like CIBERSORTx, have use-cases where they perform the best. Please let me know if you have any additional questions. 

Thanks,
Brandon

**Comment by alexdray86** [comment]
[bisqueRNA_question.pdf](https://github.com/cozygene/bisque/files/6351044/bisqueRNA_question.pdf)

I am putting you here a figure of this results. As it provides me a worst results with BisqueRNA than with a simple NNLS, I thought I should let you know. 

Best,
