### ISSUE TITLE
leave-one-out cross validation

### ISSUE THREAD

**Issue by empiricalbayes** [cozygene/bisque#21]
Hello,

I wonder if you could provide the codes you used for leave-one-out cross validation in your simulations.

Thanks.

**Comment by brandonjew** [comment]
Hi @empiricalbayes, sure thing. Please note that this is an R script, not a TXT file, so it should be renamed (made TXT to comply with attachment requirements). This script is meant to be run from the command line with a single positional argument that is an integer between 1 and 5. This argument specifies the scaling factor to simulate (one of [0, 5, 10, 15, 20]). Note that this script takes quite a long time to run with CIBERSORT and bseq-sc comparisons. If commented out, Bisque and MuSiC should complete fairly quickly.

Arguments that should be noted/edited:

- `cibersort.path` is the path to the CIBERSORT.R file (retrieved by following https://shenorrlab.github.io/bseqsc/vignettes/pages/installation.html)
- `seurat.rds` is an RDS file containing the single-cell/single-nuc object processed by Seurat
- `seurat.marker.rds` is an RDS file containing the output of `Seurat::FindAllMarkers()`
- `out.prefix` is the prefix for all cell composition output CSV files (it will output the ground truth as `{prefix}.loo.true.csv` and a file for each method, scaling factor, and replication). 

Here is the script: [simulation_analysis.txt](https://github.com/cozygene/bisque/files/6489578/simulation_analysis.txt)

Let me know if you run into any issues!

Thanks,
Brandon

**Comment by empiricalbayes** [comment]
Many thanks @brandonjew
