### ISSUE TITLE
Bulk already in CPM

### ISSUE THREAD

**Issue by iriverog** [cozygene/bisque#23]
Hi!

Great package! I would like to run Bisque with some public bulk RNA-seq datasets that are, unfortunately, only available as CPM. Is there any way I can feed it the CPM normalized data and skip the CPM normalization performed by Bisque?

Thanks for your time and help,
Inés

**Comment by brandonjew** [comment]
Hi Inés, thanks for your interest in our method! I'm a bit busy these next couple of weeks so I can't make an edit to the interface myself right now. One quick solution is just to divide your CPM data by 1e6 (each individual's gene expression profile should add up to 1 after this). Conversion of these values to CPM again should yield the same value.

Please let me know if you have any questions!

**Comment by iriverog** [comment]
Hi Brandon,

Thanks for your quick reply. Your suggestion worked, many thanks. I'll close the issue now.

Inés
