### ISSUE TITLE
how to prepare single cell input from multiple subjects as an input?

### ISSUE THREAD

**Issue by complexgenome** [cozygene/bisque#25]
Hi there,
I am interested to use bisque for single-cell deconvolution on bulk RNA sequenced individuals. 

The tutorial/methods require to prepare single-cell input where multiple subjects' data are present in it. I have .Rds file per subject for the single-cell.
How do I prepare input object from these per-subject single-cell raw counts?
   
best,

**Comment by brandonjew** [comment]
Hi @sariya, thanks for your interest! It depends on the data structure that is storing the single-cell data. If they are Seurat objects, you can merge them by following their tutorial: https://satijalab.org/seurat/archive/v3.1/merge_vignette.html
