### ISSUE TITLE
sim.data average proportions taking into account variation between replicates

### ISSUE THREAD

**Issue by emmawwinchester** [cozygene/bisque#26]
Hello there! 
I am using bisque with pretty great success, our correlation values look awesome!!
However I have noticed something that I can't seem to figure out a workaround for. 
Our single cell dataset has 4 replicates included in it, each with naturally varying proportions of each cell type. However, in order to generate the simulation data to obtain an r2 correlation value between actual and predicted proportions, the input requires a single proportion number for each cell type rather than taking into account the already occurring variation in proportion across replicates. 
I have not seen a way to incorporate a list of proportions across replicates into this simulation data, but maybe I'm missing something!
Thank you,
Emma

**Comment by brandonjew** [comment]
Hi Emma, thanks for your interest in our method! Unfortunately, our method cannot incorporate additional information from replicates. For this approach, we would just use something like the mean
