### ISSUE TITLE
Use FPKM or CPM value of bulk RNA seq as input matrix

### ISSUE THREAD

**Issue by bugie19** [cozygene/bisque#28]
Thanks for this amazing tool !!
i have one question regarding this tool, is it possible to use FPKM value of bulk RNA seq as an input matrix instead of using gene count matrix as paper suggested?

Thanks.

Bugie

**Comment by brandonjew** [comment]
Hi Bugie, 

Thank you for your interest in our method! CPM can be used, since the CPM transformation should give the same value. However, FPKM cannot currently be used as input and was not tested for our approach. Please let me know if you have any additional questions!

Thanks again,
Brandon
