### ISSUE TITLE
Microarray data?

### ISSUE THREAD

**Issue by Yoshi-MutoLab** [cozygene/bisque#30]
Hi,

Thank you for developing such a useful software - really helpful. I am wondering if we could also utilize bisque for deconvolution of published microarray datasets. Do you think it is possible? If so, what is your recommendation for preprocessing of microarray data?

Best,
Yoshi

**Comment by brandonjew** [comment]
Hi Yoshi,

Thank you for your interest in our method! Unfortunately, Bisque is not currently designed for microarray data. Other methods, such as CIBERSORTx, have been designed with these data in mind.

Brandon
