### ISSUE TITLE
 visualization

### ISSUE THREAD

**Issue by chenx9** [cozygene/bisque#32]
Hi, thank you for providing such a useful tool, I now have a question about how I can achieve visualization when I have the results 'res', as shown in Figure 4A.

**Comment by brandonjew** [comment]
Hi @chenx9, we used the seaborn python package to generate those plots. Specifically, it is a strip plot on top of a box plot. You can see an example of the plot here: https://seaborn.pydata.org/generated/seaborn.stripplot.html (plot under "Draw strips of observations on top of a box plot"). This can be done in R with ggplot as well: https://ggplot2.tidyverse.org/reference/geom_jitter.html
