### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by Yuling-Zhao** [cozygene/bisque#34]
Dear authors,

I am new to scRNAseq analysis. I read the Bisque paper and want to learn this powerful tool. I have bulk RNAseq data and collected published scRNA seq data of my cells of interest. However, I am stuck at the very beginning about the input format requirement. Do you mind addressing some data for practice in the repository? For example, what does the input matrix of bulk RNAseq counts look like, how did you get character vectors of cell type labels and individual labels? 

I understand this could be extra work for you. I hope this can be added and more beginners like me will benefit.

Thanks for your help in advance!

Best,
Yuling

**Comment by brandonjew** [comment]
Hi Yuling,

Thank you for your interest in our method. There is a vignette here that provides more detail on using the package: https://cran.r-project.org/web/packages/BisqueRNA/vignettes/bisque.html

The character vectors for cell type labels and individuals are typically retrieved from the Seurat object holding the scRNA-seq data.

Best,
Brandon
