### ISSUE TITLE
Lack of "ground truth"markers and estimation

### ISSUE THREAD

**Issue by ssamberkar** [cozygene/bisque#36]
Hi,

I've been using Bisque to deconvolute a bulk RNAseq dataset using known marker genes, obtained from a scRNAseq experiment. While the workflow is easy to follow and useful, I have 2 questions:

1) Can I obtain expressions of these marker genes in the bulk RNAseq data, by multiplying the obtained estimates with the normalised counts?

2) How do I determine the accuracy of the estimated proportions in the absence of ground truth? It may sound rhetorical but I was wondering the approaches to this issue.

Thoughts?

Best,
Sandeep

**Comment by brandonjew** [comment]
Hi @ssamberkar,

Thanks for your interest in our method.

1. To clarify, are you interested in retrieving cell-type-specific gene expression for each of the markers? If so, it's a more complex process to estimate those values from bulk RNA-seq data. Some available methods for estimating cell-type-specific expression profiles include [bMIND](https://genome.cshlp.org/content/31/10/1807.full) and [BayesPrism](https://www.nature.com/articles/s43018-022-00356-3), the latter of which also estimates cell type proportions.
2. Without experimental data, like FACS-based counts for a subset of the data, there is no straightforward way to do this. Trusting the estimates from a method depends on how similar your application is to the validation used in the manuscript, and experimental validation is always a good idea if possible. Methods like CIBERSORT do provide a p-value indicating the significance of the proportion estimates (although the null hypothesis is that no cell types are present, so a significant result may not mean much).

Let me know if you have any other questions.

Thanks,
Brandon
