### ISSUE TITLE
Negative proportion values

### ISSUE THREAD

**Issue by ssamberkar** [cozygene/bisque#37]
Hi Justin,

We've been extensively testing Bisque for our deconvolution use case, specifically Marker based Decomposition. From our results and also from your vignette, the bulk.props matrix has negative values. How to interpret these results? Surely the cell-type proportions can't be negative? 

Apologies for a naive question and raising an issue for it.

Best,
Sandeep

**Comment by brandonjew** [comment]
Hi Sandeep,

Thank you for your interest in our method! The values from the marker-based decomposition function are not proportions. The marker-based decomposition provides relative abundance measurements, meaning you can only use them to compare samples to one another (ex. Sample A with negative value for a cell type is estimated to have less abundance than Samble B with a positive value for the cell type, but the exact difference in proportion is not known). Please let me know if you have any other questions.

Thanks,
Brandon
