### ISSUE TITLE
Can I use TCGA's TPM data format for bulk RNA as input to bisque?

### ISSUE THREAD

**Issue by suhuanhou** [cozygene/bisque#40]
Looking forward to the author's answer, thanks!

**Comment by brandonjew** [comment]
Hi @suhuanhou,

Thank you for your interest in our method! Bisque expects a counts matrix and internally performs CPM normalization. While applying CPM normalization on top of TPM normalization gives you the same TPM values, the results in the manuscript are based off of CPM normalization alone. Bisque's behavior with TPM values has not been tested and we suggest adhering to the raw counts input. 

Best,
Brandon
