### ISSUE TITLE
bisque in conda-forge / bioconda

### ISSUE THREAD

**Issue by favilaco** [cozygene/bisque#5]
Hi,

Would it be possible for you to deposit bisque in conda-forge / bioconda ?

Best,

Francisco

**Comment by brandonjew** [comment]
Hi Francisco,

I will add bisque to Bioconda, I will let you know here when the process is complete.

Thanks,
Brandon

**Comment by brandonjew** [comment]
Hi Francisco,

Thank you for your suggestion, Bisque is now on Bioconda as r-bisquerna

Brandon
