### ISSUE TITLE
Errors in MarkerBasedDecomposition

### ISSUE THREAD

**Issue by yuewangpanda** [cozygene/bisque#7]
Hi Brandon,

I want to use the BisqueRNA package to infer the cell types of my bulk data. I have my own markers and am using MarkerBasedDecomposition function. However, with different cutoffs of min_gene, I got different errors. 

res <- MarkerBasedDecomposition(bulk.eset, markers = mymarker)
The error was "Clusters must have a minimum of 5 unique marker genes"

res <- MarkerBasedDecomposition(bulk.eset, markers = mymarker, min_gene = 1)
The error was "Error in base::eigen(varcov):infinite or missing values in 'x'"

res <- MarkerBasedDecomposition(bulk.eset, markers = mymarker, min_gene = 1)
The error was "Error in base::eigen(varcov):infinite or missing values in 'x'"

res <- MarkerBasedDecomposition(bulk.eset, markers = mymarker, min_gene = 2)
The error was "Error in 1:ng: argument of length 0".

I attached the bulk data and markers I used.
[exampleData.rda.zip](https://github.com/cozygene/bisque/files/3918606/exampleData.rda.zip)

Please help me out.

Thanks,
Frank

**Comment by brandonjew** [comment]
Hi Frank,

We diagnosed the bug and will push the fixes soon. The errors are due to a cell-type with only one marker gene. This should be avoided since the marker-based decomposition uses a PCA-based approach that does not apply to cases with only one gene. I'll let you know when the package is updated. 

Thanks,
Brandon

**Comment by brandonjew** [comment]
Package has been updated on GitHub. Let me know if there are still any issues. The update has not propagated to CRAN or Bioconda yet, so you'll need to manually update if you need it immediately

**Comment by yuewangpanda** [comment]
Thank you for the updates. It works well now. Still have a quick question:
what are the values of the bulk.props? My understanding is the weight of
the similarity of a sample (bulk) and a cluster (single-cell). Correct me
if I don't get it.

Thanks,
Frank

**Comment by marcalva** [comment]
Hi Frank, the bulk.props contains (relative) cell type proportions estimates for each sample. These are principal component scores and so they do not represent true proportions. So samples with higher values for a cell type will have overall higher expression of that cell type's marker genes. Hope this make sense!

Thanks,
Marcus

**Comment by yuewangpanda** [comment]
Hi Marcus,

Clear explanation. However, in my case, some of the values are negative. Is
it correct?

Best,
Frank

**Comment by marcalva** [comment]
Hi Frank,

That is correct. Some values can certainly be negative.

Best,
Marcus
