### ISSUE TITLE
CountsToCPM after extracting markers

### ISSUE THREAD

**Issue by randel** [cozygene/bisque#9]
Thanks for the new approach! In `ReferenceBasedDecomposition`, if `markers` are provided, only sc and bulk data of those markers are taken to CountsToCPM. Does it make sense to calculate CPM for (say hundreds of) marker genes only? Or it makes more sense to calculate CPM for all genes and then take the subset of markers?

https://github.com/cozygene/bisque/blob/ef5bae05fb011fbc0f516078377cd3a6fc7fad4d/R/reference_based.R#L298-L315

**Comment by brandonjew** [comment]
Hi @randel, thanks for your interest in our method and the great question!

I can see how this is an issue for cases like the extreme example of only having one marker gene (every sample would have values of 0 or 1,000,000, including the reference). I am assuming that this issue becomes less significant as more marker genes as used; however, I will look into switching the order of operations here to avoid this issue from popping up. Thanks for pointing this out! I'll close this issue after I've finished testing.

**Comment by brandonjew** [comment]
added an option `old.cpm` to change the ordering. kept as an option for replicating older results. thanks!
